### PR TITLE
R pkg array df2 chunks

### PR DESCRIPTION
**Pull request by mcolosimo-p4**
Added `Array$data_frame_to_chunks` and supporting functions (with moving some common code out). Also some additional bug fixes that were exposed when adding new tests for chunking a data.frame.

### CODE REVIEW

**Comment by rvernica** [comment]
Since you have tests for the R package, let's see if we can get them to run in GitHub Actions. Let me try to add a GitHub Actions Workflow to your branch before we merge it.

**Comment by rvernica** [comment]
@mcolosimo-p4 do you have any specific R versions you want the R code tested against?

**Comment by rvernica** [comment]
I added `.github/workflow/test-scidb-ee-r.yml` to this branch. It tires to setup R and run the tests in the R package.

**Comment by mcolosimo-p4** [comment]
@rvernica I think our current R base is 3.6.0 (or 3.6.4 maybe on some systems).

I have more updates and tests that I'm adding.

**Comment by rvernica** [comment]
@mcolosimo-p4 @mpeterson-p4 I managed to setup the R environment for GitHub Actions. It produces some warnings and errors. It appears that it tries to run the tests but the `scidb` package is missing from the requirements list. You can probably repro this locally by running `rcmdcheck` against the package, similarly with how we have it in the GitHub Actions workflow.

See here: https://github.com/Paradigm4/bridge/runs/3783007554?check_suite_focus=true

**Comment by mcolosimo-p4** [comment]
abandoning this PR and starting a new one based off of branch v19.11

**Pull request closed without merging**
